version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED:"1"

networks:
  helix-network:
    external: true